---
title: "LAB1"
author: Смирнов Михаил
format:
   md:
     output-file: README.md
engine: knitr
---
```{r echo=TRUE}
5+7
```
```{r echo=TRUE}
x <-5+7
x
y <-x-3
y
```
```{r}
z<-c(1.1,9,3.14)
z
```
```{r}
z<-555
c(z,555,z)
```
```{r}
z*2+100
```
```{r}
my_sqrt<-sqrt(z-1)
my_sqrt
```
```{r}
my_div <- z / my_sqrt
z * 2 + 1000
```
## 2 | In this lesson, you'll learn how to examine your local workspace in R and begin to explore the
##| relationship between your workspace and the file system of your machine.

```{r}
getwd()
ls()
x<-9
ls()
list.files()
?list.files
args(list.files)
old.dir <- getwd()
dir.create("testdir")
setwd("testdir")
file.create("mytest.R")
list.files
file.exists("mytest.R")
file.info("mytest.R")
file.rename("mytest.R","mytest2.R")
file.copy("mytest2.R", "mytest3.R")
file.path("mytest3.R")
file.path("folder1", "folder2")
dir.create(file.path("testdir2","testdir3"),recursive = TRUE)
setwd(old.dir)

```
##  3 | In this lesson, you'll learn how to create sequences of numbers in R.
```{r}
1:20
pi:10
15:1
?":"
seq(1,20)
seq(0, 10, by=0.5)
seq(5, 10, length=30)
my_seq <- seq(5, 10, length=30)
length(my_seq)
1:length(my_seq)
seq(along.with = my_seq)
seq_along(my_seq)
rep(0, times = 40)
rep(c(0, 1, 2), times = 10)
rep(c(0, 1, 2), each = 10)
```
## 4 | The simplest and most common data structure in R is the vector.
```{r}
num_vect <- c(0.5,55,-10,6)
num_vect < 1
tf <- num_vect < 1
tf
num_vect >= 6
my_char <- c("My","name","is")
my_char
paste(my_char, collapse = " ")
c(my_char, "Mikhail")s
my_name
paste(my_name,collapse = " ")
paste("Hello", "world!", sep = " ")
paste(1:3, c("X", "Y", "Z"), sep = "")
paste(LETTERS, 1:4, sep = "-")

```

